### ISSUE TITLE
Error on getting a collection by Id

### ISSUE THREAD

**Issue by irineul** [henriquecarv/loopback-connector-realtime-database#175]
1. I create collection
2. I run the GET (to return all collections), and it returns:

```
[
  {
    "id": "-LwU90TtYEcnFCmworbQ",
    "cnpj": "saease",
    "name": "esaes",
    "qty_spots": 1
  },
  {
    "id": "-LwUAxrOD3p3jOOEuU2d",
    "cnpj": "esasea",
    "name": "esaesa",
    "qty_spots": 1
  },
  {
    "id": "-LwUG_rxD2UX0B1snn81",
    "cnpj": "test",
    "name": "xjxjx",
    "qty_spots": 2
  }
]
```

3. I run the endpoint GET /{id}:
curl -X GET "http://localhost:3000/testing/-LwUG_rxD2UX0B1snn81" -H "accept: application/json"

4. And is not possible to find the entity: **"ENTITY_NOT_FOUND"**

What can I do to fix that?

**Comment by henriquecarv** [comment]
If I'm not mistaken you should be encoding the filter parameters:

http://localhost:3000/testing?filter[where][id]=-LwUG_rxD2UX0B1snn81

Ref: https://loopback.io/doc/en/lb3/Where-filter.html

**Comment by irineul** [comment]
Hi @henriquecarv 

I tried to do this too. It gives an error:

```
Unhandled error in GET /parks/?filter[where][id]=-LwUG_rxD2UX0B1snn81: 500 TypeError: models.map is not a function
    at ParkRepository.toEntities (/Users/irineul/Desktop/CODE/pms-mobile-api-v2/pms-mobile-api/node_modules/@loopback/repository/src/repositories/legacy-juggler-bridge.ts:507:19)
    at ParkRepository.find (/Users/irineul/Desktop/CODE/pms-mobile-api-v2/pms-mobile-api/node_modules/@loopback/repository/src/repositories/legacy-juggler-bridge.ts:375:27)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
```

**Comment by sudipta-b** [comment]
I am having the same issue in loopback 4, any hints would be really helpful.
