### ISSUE TITLE
"or" and "and" operators do not works

### ISSUE THREAD

**Issue by Fr4nZ82** [henriquecarv/loopback-connector-realtime-database#216]
# Describe the bug

Do not know if is a feature request or a bug, but queries with filters like `where: { and: [ { item: 'somestring' }, { deleted: false } ] }` do not works.
```
error Error: Query: First argument passed to startAt(), endAt(), or equalTo() cannot be an object.
    at Function.Query.validateQueryEndpoints_ (C:\progetti\mydisplayserver\node_modules\@firebase\database\src\api\Query.ts:138:15)
    at Query.startAt (C:\progetti\mydisplayserver\node_modules\@firebase\database\src\api\Query.ts:509:11)
    at Query.equalTo (C:\progetti\mydisplayserver\node_modules\@firebase\database\src\api\Query.ts:574:17)
    at RealtimeDatabase.queryData (C:\progetti\mydisplayserver\node_modules\loopback-connector-realtime-database\lib\realtime-database.js:81:10)
    at RealtimeDatabase.all (C:\progetti\mydisplayserver\node_modules\loopback-connector-realtime-database\lib\realtime-database.js:57:33)
    at invokeConnectorMethod (C:\progetti\mydisplayserver\node_modules\loopback-datasource-juggler\lib\dao.js:172:21)
    at C:\progetti\mydisplayserver\node_modules\loopback-datasource-juggler\lib\dao.js:1730:7
    at doNotify (C:\progetti\mydisplayserver\node_modules\loopback-datasource-juggler\lib\observer.js:157:49)
    at doNotify (C:\progetti\mydisplayserver\node_modules\loopback-datasource-juggler\lib\observer.js:157:49)
    at Function.ObserverMixin._notifyBaseObservers (C:\progetti\mydisplayserver\node_modules\loopback-datasource-juggler\lib\observer.js:180:5)
    at Function.ObserverMixin.notifyObserversOf (C:\progetti\mydisplayserver\node_modules\loopback-datasource-juggler\lib\observer.js:155:8)
    at Function.ObserverMixin._notifyBaseObservers (C:\progetti\mydisplayserver\node_modules\loopback-datasource-juggler\lib\observer.js:178:15)
    at Function.ObserverMixin.notifyObserversOf (C:\progetti\mydisplayserver\node_modules\loopback-datasource-juggler\lib\observer.js:155:8)
    at Function.find (C:\progetti\mydisplayserver\node_modules\loopback-datasource-juggler\lib\dao.js:1728:10)
    at Function.findOne (C:\progetti\mydisplayserver\node_modules\loopback-datasource-juggler\lib\dao.js:1775:8)
    at UserRepository.findOne (C:\progetti\mydisplayserver\node_modules\@loopback\repository\src\repositories\legacy-juggler-bridge.ts:405:23)
    at UserController.register (C:\progetti\mydisplayserver\src\controllers\user.controller.ts:236:53)
```

**Comment by henriquecarv** [comment]
It hasn't been implemented in this connector yet.

I will try to look at it when I have some time, but feel free to attempt a solution for this. I am sure, a lot of people could also benefit from it.
